name: Deploy

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          git fetch --prune --unshallow
          wget --secure-protocol=TLSv1 https://clever-tools.cellar.services.clever-cloud.com/releases/latest/clever-tools-latest_linux.tar.gz
          tar xvzf clever-tools-latest_linux.tar.gz

      - name: Login Clever Cloud
        run: ./clever-tools-latest_linux/clever login --token ${{secrets.CLEVER_TOKEN}} --secret ${{secrets.CLEVER_SECRET}}

      - name: Build Dockerfile
        run: |
          ./clever-tools-latest_linux/clever deploy -a app-react
